# Generated by Django 5.0.4 on 2024-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
