# Generated by Django 5.0.4 on 2024-04-23 09:33

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupForm', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('waste_type', models.CharField(max_length=50)),
                ('disposer', models.CharField(max_length=50)),
                ('value', models.IntegerField(max_length=20)),
                ('recycling_method', models.CharField(max_length=50)),
                ('recycle_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='password2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
