# Generated by Django 5.0.4 on 2024-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupForm', '0003_wastedetails_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedetails',
            name='recycling_method',
            field=models.CharField(choices=[('MATERIAL', 'stoffliche Entsorgung'), ('DISPOSAL', 'Beseitigung'), ('ENERGETIC', 'energetische Entsorgung')], default='DISPOSAL', max_length=50),
        ),
    ]
