# Generated by Django 5.0.4 on 2024-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupForm', '0004_alter_wastedetails_recycling_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedetails',
            name='recycling_method',
            field=models.CharField(choices=[('MATERIAL', 'stoffliche Entsorgung'), ('ENERGETIC', 'energetische Entsorgung'), ('DISPOSAL', 'Beseitigung')], default='DISPOSAL', max_length=50),
        ),
    ]
